main/urls.py
from django.conf.urls import url, include
from . import views
from seminario import settings
from django.contrib.auth import views as auth_views
from django.views import(
	static
	)

urlpatterns = [
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^c/$', views.CompraList.as_view(), name='compra_all'),

    url(r'^p/(?P<pk>\d+)/$', views.ProductoDetail.as_view(), name='producto_detail'),
    url(r'^p/add/$', views.ProductoView.as_view(), name='producto_add'),
    url(r'^p/$', views.ProductoList.as_view(), name='producto_all'),

    url(r'^c/add/$', views.CompraAdd.as_view(), name='compra_add'),
    url(r'^c/precio/add/$', views.PrecioCompraAdd.as_view(), name='compra_precio_add'),

    url(r'^v/add/$', views.VentaAdd.as_view(), name='venta_add'),
    url(r'^v/precio/add/$', views.PrecioVentaAdd.as_view(), name='venta_precio_add'),
    url(r'^v/$', views.VentaList.as_view(), name='venta_all'),

    url(r'^perfil/(?P<pk>\d+)/$', views.PerfilView.as_view(), name='perfil'),

    url(r'^bi/$', views.Analytics.as_view(), name='analytics'),
    url(r'^bi/api/$', views.AnalyticsApi.as_view(), name='analytics_api'),

    url(r'^$', views.ProductoView.as_view(), name='home'),

]

seminario/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/models.py
import os
from django.db import models
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from datetime import timedelta, date, time
from django.utils import timezone

from easy_thumbnails.fields import ThumbnailerImageField

class Perfil(models.Model):
    GENERO_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dpi = models.CharField(max_length=20, unique=True)
    public = models.BooleanField(default=True)
    genero = models.CharField(max_length=1, choices=GENERO_CHOICES, default='M')
    fecha_nacimiento = models.DateField(null=True, blank=True)
    direccion = models.CharField(max_length=150, null=True, blank=True)
    foto = ThumbnailerImageField(
        upload_to="perfil_usuario",
        null=True,
        blank=True,
        editable=True,)
    objects = models.Manager()

    def get_nombre(self):
        return self.user.first_name
    nombre = property(get_nombre)

    def get_apellido(self):
        return self.user.last_name
    apellido = property(get_apellido)

    def get_absolute_url(self):
        return reverse_lazy('perfil', kwargs={'pk': self.id})

    class Meta:
        verbose_name = 'perfil'
        verbose_name_plural = 'perfiles'

    def __str__(self):
        return self.nombre + " " + self.apellido

class Producto(models.Model):
    nombre = models.CharField(max_length=150)

    def get_absolute_url(self):
        return reverse_lazy('producto_detail', kwargs={'pk': self.id})

    def precio_compra_actual(self, fecha=date.today()):
        ultimo_precio = CompraPrecio.objects.filter(fecha__lte=fecha, producto=self).order_by('fecha').reverse()
        if ultimo_precio.count() < 1:
            return None
        else:
            return ultimo_precio[0]
    precio_compra_actual = property(precio_compra_actual)

    def precio_venta_actual(self,fecha=date.today()):
        ultimo_precio = VentaPrecio.objects.filter(fecha__lte=fecha, producto=self).order_by('fecha').reverse()
        if ultimo_precio.count() < 1:
            return None
        else:
            return ultimo_precio[0]
    precio_venta_actual = property(precio_venta_actual)

    def compras(self):
        compra_list = Compra.objects.filter(producto=self)
        if compra_list.count() < 1:
            return 0
        else:
            return sum(compra.cantidad for compra in compra_list)
    compras = property(compras)

    def ventas(self):
        venta_list = VentaDetalle.objects.filter(producto=self)
        if venta_list.count() < 1:
            return 0
        else:
            return sum(venta.cantidad for venta in venta_list)
    ventas = property(ventas)

    def existencia(self):
        return self.compras - self.ventas
    existencia = property(existencia)

    def __str__(self):
        return str(self.nombre)

class Compra(models.Model):
    producto = models.ForeignKey('Producto', related_name='compra')
    cantidad = models.IntegerField()
    fecha = models.DateField(default=timezone.now)

    def get_precio(self):
        precio = CompraPrecio.objects.filter(producto=self.producto, fecha__lte=self.fecha).order_by('fecha').last()
        if precio:
            return precio.precio
        else:
            return 0
        
    precio = property(get_precio)

    def total(self):
        return self.cantidad * self.precio

    def __str__(self):
        return "No. " + str(self.id) + " - (" + str(self.fecha) + ")"

class CompraPrecio(models.Model):
    producto = models.ForeignKey('Producto', related_name='precio_compra')
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    fecha = models.DateField(default=timezone.now)

    class Meta:
        unique_together = ('producto', 'fecha')


    def __str__(self):
        return str(self.producto)+ " - " + str(self.fecha) + " - " + str(self.precio)
        

class Venta(models.Model):
    vendedor = models.ForeignKey('Perfil', related_name='venta')
    fecha = models.DateField(default=timezone.now)

    def __str__(self):
        return "No. " + str(self.id) + " - (" + str(self.fecha) + ")"

class VentaPrecio(models.Model):
    producto = models.ForeignKey('Producto', related_name='precio_venta')
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    fecha = models.DateField(default=timezone.now)
    
    class Meta:
        unique_together = ('producto', 'fecha')

    def __str__(self):
        return str(self.precio)

class VentaDetalle(models.Model):
    venta = models.ForeignKey('Venta', related_name='detalle_venta')
    producto = models.ForeignKey('Producto', related_name='venta')
    cantidad = models.IntegerField()

    def get_precio(self):
        precio = VentaPrecio.objects.filter(producto=self.producto, fecha__lte=self.venta.fecha).order_by('fecha').last()
        if precio:
            return precio.precio
        else:
            return 0

    precio = property(get_precio)

    def total(self):
        return self.cantidad * self.precio

    def __str__(self):
        return str(self.producto) + " - " + str(self.cantidad)

main/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import *
from django.forms.models import inlineformset_factory

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
        'nombre': forms.TextInput(attrs={'class': 'form-control border-input'})
        }

class VentaPrecioForm(ModelForm):
    class Meta:
        model = VentaPrecio
        fields = ('producto', 'precio',)
        widgets = {
        'producto': forms.Select(attrs={'class': 'form-control border-input'}),
        'precio': forms.NumberInput(attrs={'class': 'form-control border-input'}),
        }

class CompraPrecioForm(ModelForm):
    class Meta:
        model = CompraPrecio
        fields = ('producto', 'precio',)
        widgets = {
        'producto': forms.Select(attrs={'class': 'form-control border-input'}),
        'precio': forms.NumberInput(attrs={'class': 'form-control border-input'}),
        }

class CompraForm(ModelForm):
    class Meta:
        model = Compra
        fields = '__all__'
        widgets = {
        'producto': forms.Select(attrs={'class': 'form-control select2'}),
        'cantidad': forms.NumberInput(attrs={'class': 'form-control', 'min': 1})}

    def clean(self):
        cleaned_data = super(CompraForm, self).clean()
        if CompraPrecio.objects.filter(producto=cleaned_data['producto']).count() == 0:
            raise forms.ValidationError(
                 "El producto aún no tiene un precio de compra asignado"
                )

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = '__all__'
        exclude = ('vendedor',)


VentaDetalleFormSet = inlineformset_factory(
    Venta,
    VentaDetalle,
    fields='__all__',
    extra=1,
    can_delete=False,
    widgets={
        'producto': forms.Select(attrs={'class': 'form-control'}),
        'cantidad': forms.NumberInput(attrs={'class': 'form-control'})})
PrecioVentaFormSet = inlineformset_factory(Producto, VentaPrecio, fields='__all__',extra=1, can_delete=False)


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = '__all__'
        exclude = ('user', 'public')

main/views.py
import json
from django.http import HttpResponse
from django.db.models import Count, Sum
from django.shortcuts import render, redirect, get_object_or_404
from main.models import *
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from main.forms import *
from main.mixins import VentaContextMixin
from main.bi import *
from braces.views import LoginRequiredMixin


def compra_all(request):
    compra_list = Compra.objects.all()
    context = {
        'compra_list': compra_list
    }
    return render(request, 'compra/all.html', context)


class ProductoList(LoginRequiredMixin, ListView):
    model = Producto
    template_name = 'producto/all.html'


class ProductoView(LoginRequiredMixin, CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'producto/add.html'
    success_url = reverse_lazy('producto_add')

    def get_context_data(self, **kwargs):
        context = super(ProductoView, self).get_context_data(**kwargs)
        context['producto_list'] = Producto.objects.all()
        return context


class ProductoDetail(LoginRequiredMixin, DetailView):
    model = Producto
    template_name = 'producto/detail.html'


class PrecioVentaAdd(LoginRequiredMixin, CreateView):
    model = VentaPrecio
    form_class = VentaPrecioForm
    template_name = 'venta/precio_add.html'
    success_url = reverse_lazy('producto_add')


class PrecioCompraAdd(CreateView):
    model = CompraPrecio
    form_class = CompraPrecioForm
    template_name = 'compra/precio_add.html'
    success_url = reverse_lazy('producto_add')


class CompraAdd(CreateView):
    model = Compra
    form_class = CompraForm
    template_name = 'compra/form.html'
    success_url = reverse_lazy('compra_all')


class CompraList(LoginRequiredMixin, ListView):
    model = Compra
    template_name = 'compra/all.html'


class VentaAdd(VentaContextMixin, CreateView):
    model = Venta
    template_name = 'venta/add.html'
    success_url = reverse_lazy('producto_add')
    form_class = VentaForm

    def form_valid(self, form):
        form.instance.vendedor = self.request.user.perfil
        return super(VentaAdd, self).form_valid(form)


class VentaList(LoginRequiredMixin, ListView):
    model = VentaDetalle
    template_name = 'venta/all.html'


class PerfilView(LoginRequiredMixin, UpdateView):
    template_name = 'user/perfil.html'
    form_class = PerfilForm
    model = Perfil

class Analytics(LoginRequiredMixin, TemplateView):
    template_name = "bi/home.html"
    def get_context_data(self, **kwargs):
        context = super(Analytics, self).get_context_data(**kwargs)
        resumen = []
        mes = Calendario().get_mes_actual()
        for dia in mes:
            resumen.append({
                'dia': dia,
                'ventas': Venta.objects.filter(fecha=dia),
                'compras': Compra.objects.filter(fecha=dia),
                })
        context['resumen'] = resumen
        return context

class AnalyticsApi(LoginRequiredMixin, TemplateView):
    def get(self, request):
        qs = self.analyze_producto(request.GET.get('inicio', None), request.GET.get('fin', None))
        qs_vendedor = self.analyze_vendedor(request.GET.get('inicio', None), request.GET.get('fin', None))

        return HttpResponse(
            json.dumps({
                'productos': qs,
                'vendedores': qs_vendedor})
            )

    def analyze_producto(self, fecha_inicio=None, fecha_fin=None):
        venta_list = Venta.objects.all()
        compra_list = Compra.objects.all()
        if fecha_inicio:
            venta_list = venta_list.filter(fecha__gte=fecha_inicio)
            compra_list = compra_list.filter(fecha__gte=fecha_inicio)
        if fecha_fin:
            venta_list = venta_list.filter(fecha__lte=fecha_fin)
            compra_list = compra_list.filter(fecha__lte=fecha_fin)

        producto_list = Producto.objects.all()

        lista = []
            

        for producto in producto_list:
            lista.append({
                'producto': producto.nombre,
                'cantidad': sum(venta.cantidad for venta in producto.venta.filter(venta__in=venta_list)),
                'cantidad_compra': sum(compra.cantidad for compra in producto.compra.filter(fecha__range=[fecha_inicio, fecha_fin])),
                })
        return lista

    def analyze_vendedor(self, fecha_inicio=None, fecha_fin=None):
        vendedor_list = Perfil.objects.all()
        lista = []
        for vendedor in vendedor_list:
            venta_list = Venta.objects.filter(vendedor=vendedor, fecha__range=[fecha_inicio, fecha_fin])
            lista.append({
                'vendedor': str(vendedor),
                'cantidad': sum(venta.cantidad for venta in VentaDetalle.objects.filter(venta__in=venta_list))
                })
        return lista

main/templates/venta/add.html
{% extends "base/base.html" %}

{% load staticfiles %}

{% block content %}
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header">
						<h3>Nueva venta</h3>
					</div>

					<div class="box-body">
						<div class="table-responsive">
							<form action="{{action}}" method="post">
								<table class="table table-hover">
									{% csrf_token %}
									{{form.as_table}}

									<tbody id="detalle_table">
										{% for form_detalle in named_formsets.detalle.forms %}
										<tr id="{{form_detalle.prefix}}-row" class="form-container-detalle">
											<td>Producto</td>
											{{ form_detalle.id }}
											<td>
												{% if form_detalle.instance.pk %}{{ form_detalle.DELETE }}{% endif %}
												{{form_detalle.producto}}
											</td>
											<td>
												{{form_detalle.cantidad}}
											</td>
										</tr>
										{% endfor %}
									</tbody>

									<tr>
										<td colspan="2" align="center">
											<input type="submit" class="btn btn-primary" value="Guardar">
										</td>
									</tr>
								</table>
								{{ named_formsets.detalle.management_form }}
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

{% block extra_js %}
<script src="{% static "js/jquery.formset.js" %}"></script>
<script type="text/javascript">
	$(function() {
		$('#detalle_table  tr').formset({
			prefix: "{{ named_formsets.detalle.prefix }}"
		});
		$('table.form-container-detalle').formset({
			prefix: "{{ named_formsets.detalle.prefix }}",

		});
	});
</script>
{% endblock extra_js %}

main/templates/venta/all.html
{% extends "base/base.html" %}

{% block content %}
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header">
						<h3>Detalle de ventas</h3>
					</div>

					<div class="box-body">
						<table class="table table-hover table-datatables">
							<thead>
								<tr>
									<th>Producto</th>
									<th>Fecha</th>
									<th>Cantidad</th>
									<th>Precio unitario</th>
									<th>Precio total</th>
								</tr>
							</thead>
							<tbody>
								{% for ventadetalle in ventadetalle_list %}
								<tr>
									<td>
									<a href="{{ventadetalle.producto.get_absolute_url}}">
											{{ ventadetalle.producto }}
										</a>
									</td>
									<td>{{ ventadetalle.venta.fecha }}</td>
									<td>{{ ventadetalle.cantidad }}</td>
									<td>Q. {{ ventadetalle.precio }}</td>
									<td>Q. {{ ventadetalle.total }}</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

main/templates/venta/precio_add.html
{% extends "base/base.html" %}

{% block content %}
<section class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
					<div class="box-header">
						<h3>Actualizar precios de venta</h3>
					</div>
					<div class="box-body">
						<form action="{{action}}" method="post">
							<table class="table">
								{% csrf_token %}
								{{form.as_table}}
								<tr>
									<td colspan="2" align="center">
										<input type="submit" class="btn btn-primary" value="Guardar">
									</td>
								</tr>
							</table>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}